# Generated by Django 5.1.2 on 2024-10-21 04:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='이미지 식별자')),
                ('image_file', models.ImageField(upload_to='images/%Y%m%d', verbose_name='이미지 파일')),
                ('thumbnail', models.ImageField(upload_to='images/%Y%m%d/thumbnails', verbose_name='이미지 썸네일')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='업로더')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
